// <auto-generated />
using System;
using EngineerOfRecord.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngineerOfRecord.Persistence.Migrations
{
    [DbContext(typeof(EorDbContext))]
    partial class EorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngineerOfRecord.Domain.Employee", b =>
                {
                    b.Property<string>("VantagepointEmployeeId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastSynced")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VantagepointEmployeeId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("EngineerOfRecord.Domain.EngineerOfRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LicenseExpiration")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("LicensedStates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VantagepointEmployeeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("VantagepointEmployeeId")
                        .IsUnique();

                    b.ToTable("EngineerOfRecord", (string)null);
                });

            modelBuilder.Entity("EngineerOfRecord.Domain.EngineerOfRecord", b =>
                {
                    b.HasOne("EngineerOfRecord.Domain.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("EngineerOfRecord.Domain.EngineerOfRecord", "VantagepointEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
